feat: network error handling for sso orchestrator self service
openedx/frontend-app-admin-portal pull request #1089
Opened 2023-11-14 17:11 UTC by alex-sheehan-edx

https://2u-internal.atlassian.net/browse/ENT-7617

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2023-11-14 18:10 UTC, marlonkeating requested changes
I'm not seeing the list of SSO configs update after creating a new config.


https://github.com/openedx/frontend-app-admin-portal/assets/322346/5ddba2d0-fe3a-4314-94eb-9571c95e419a

2023-11-14 18:10 UTC, marlonkeating commented on src/components/settings/SettingsSSOTab/index.jsx
> +                {/* {error && (
Not using this anymore?

2023-11-14 18:23 UTC, alex-sheehan-edx commented on src/components/settings/data/constants.js
> +export const ssoLPNetworkErrorText = `We were unable to load your SSO details due to an internal error.`;
I was following the examples of the other modal text [above](https://github.com/openedx/frontend-app-admin-portal/pull/1089/files/d8dec147f467950d50cbc031ad86d47c7d770bca#diff-0575f6750b5731d61fd3e2c8ca2df0bf5cf0454684c1419b226050497e11be0eR38-R40)

2023-11-14 18:24 UTC, alex-sheehan-edx commented on src/components/settings/SettingsSSOTab/index.jsx
> +                {/* {error && (
ah, yup! Good catch, it's just cruft

2023-11-14 18:25 UTC, alex-sheehan-edx commented on src/components/settings/SettingsSSOTab/index.jsx
> +                {infoMessage && (
interesting, this isn't changed from master, just the indentation moved with the error conditional. I'm not even sure what the info message is showing to the user.... let me look into it

2023-11-16 15:46 UTC, marlonkeating requested changes

2023-11-16 15:46 UTC, marlonkeating commented on src/components/settings/SettingsSSOTab/index.jsx
> +                  show={infoMessage.length > 0}
We're setting `infoMessage` to null when closing above.
```suggestion
                  show={infoMessage?.length > 0}
```

2023-11-16 15:51 UTC, alex-sheehan-edx commented on src/components/settings/SettingsSSOTab/SsoErrorPage.jsx
> +      onClose={() => { }}
UX has the modal as unclosable ¯\_(ツ)_/¯

2023-11-16 15:53 UTC, marlonkeating commented on src/components/settings/SettingsSSOTab/SsoErrorPage.jsx
> +      onClose={() => { }}
Would omitting the `onClose` prop or setting it to `null` have the same effect?  IMO as it stands, it looks like we forgot to fill in some placeholder code.

2023-11-16 17:12 UTC, marlonkeating approved these changes

2023-11-16 19:55 UTC, merged