fix: adding messaging for archived courses
openedx/frontend-app-admin-portal pull request #1158
Opened 2024-01-19 14:30 UTC by kiram15

https://github.com/openedx/frontend-app-admin-portal/assets/31229189/c87fa429-e9fa-46dd-9700-b8721dcade02

To test locally, add `?feature= HIGHLIGHTS_ARCHIVE_MESSAGING`  to the end of your url. 

# For all changes

- [x] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [x] Ensure to attach screenshots
- [x] Ensure to have UX team confirm screenshots

2024-01-19 14:31 UTC, kiram15 commented on src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx
> +            <Button variant="outline-primary">Delete archived courses</Button>
The implementation of this button is covered in the work of a future ticket.

2024-01-19 16:50 UTC, marlonkeating requested changes

2024-01-19 16:50 UTC, marlonkeating commented on src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx
> +        }
Is the goal here to only push the highlighted content into archivedContent once if all course runs in it are archived?  Right now, seems to be pushing the same highlighted content into archivedContent for each archived course run in it.

2024-01-19 16:50 UTC, marlonkeating commented on src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx
> +      }
Indentation for `hyperlinkAttrs` looks off.  Optionally might consider putting the whole `ContentHighlightCardItem` generation into a helper method to aid in readability.

2024-01-19 16:50 UTC, marlonkeating commented on src/components/ContentHighlights/data/constants.js
> +        course_run_statuses: ['archived'],
Would put 'archived' and 'published' into their own constants since they're used repeatedly in the code.

2024-01-22 16:26 UTC, marlonkeating approved these changes

2024-01-22 16:27 UTC, merged