fix: allowing members table to select all
openedx/frontend-app-admin-portal pull request #1241
Opened 2024-05-28 21:31 UTC by alex-sheehan-edx

[ENT-9023](https://2u-internal.atlassian.net/browse/ENT-9023)

Page selected, not all records:
![image](https://github.com/openedx/frontend-app-admin-portal/assets/67655836/c7cf3382-7e1b-451b-b2ee-914e09974048)

Page all records selected: 
![image](https://github.com/openedx/frontend-app-admin-portal/assets/67655836/9a8ae3c4-32fa-4144-9776-90ce1ed80755)

2024-05-28 23:36 UTC, marlonkeating requested changes
Though the text is corrected when all records are selected, it still seems to only delete the first page of results.

https://github.com/openedx/frontend-app-admin-portal/assets/322346/07923950-3947-49c7-8c65-ecdaad4f25b2

2024-05-29 18:52 UTC, alex-sheehan-edx commented on src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
> +    userEvent.click(screen.getByTestId('members-table-enrollments-column-header'));
This was done, I just had forgotten to uncomment on a previous ticket.

2024-05-29 20:07 UTC, katrinan029 requested changes
Tested on stage and the select all is working as expected with the exception of the remove learners. I think we could wait to merge this PR after https://github.com/openedx/edx-enterprise/pull/2114/files gets merged and deployed to stage so that we can test the remove learners functionality

2024-05-29 20:07 UTC, katrinan029 commented on src/components/learner-credit-management/members-tab/GroupMembersCsvDownloadTableAction.jsx
> +    buttonSelectedNumber = isEntireTableSelected ? tableInstance.itemCount : selectedEmailCount;
[issue] small missing detail but there should be parenthesis around the selected number of learners in the download button e.g. `Download (12)`

perhaps something like this and update the unit test as such:

```
buttonSelectedNumber = isEntireTableSelected ? `(${tableInstance.itemCount})` : `(${selectedEmailCount})`;
```

2024-05-29 20:07 UTC, katrinan029 commented on src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
> +    const downloadButton = screen.getByText('Download 1');
based on the feedback above, this should be updated to `Download (1)` to match figma mocks.

2024-05-31 16:30 UTC, marlonkeating requested changes
Now getting an error when trying to delete all learners: "learner_emails: This field is required"
![image](https://github.com/openedx/frontend-app-admin-portal/assets/322346/db1c28a7-4334-44b0-acd8-5523c8ffb8d7)

2024-05-31 17:15 UTC, marlonkeating approved these changes

2024-05-31 17:23 UTC, katrinan029 approved these changes

2024-05-31 17:27 UTC, merged