[ENT-9538]: Make analytics V2 skills scatter chart bubble marker size consistent with V1
openedx/frontend-app-admin-portal pull request #1324
Opened 2024-10-01 08:23 UTC by mahamakifdar19

**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9538

**Description**
In Analytics V2, the marker size for skills scatter chart is not similar to what we have in scatter chart in V1. 
This PR addresses this issues and incorporates changes to make the bubble marker size consistent with V1.

**Screenshots**

**APSCHE V2 Before**
<img width="1376" alt="AP Before" src="https://github.com/user-attachments/assets/51663249-7ba3-47bb-80de-1fa4b46f0f08">

**APSCHE V2 After**
<img width="1372" alt="AP After" src="https://github.com/user-attachments/assets/f86dbdf7-b98f-4898-8b2d-5ff18bbd8d84">

**5CA V2 Before**
<img width="1382" alt="5CA - Before" src="https://github.com/user-attachments/assets/5a8f8a6a-5c0d-4075-b912-53a1b0a7d54f">

**5CA V2 After**
<img width="1382" alt="5CA - After" src="https://github.com/user-attachments/assets/ad4020d3-c50b-42f9-bff3-da655c5f0986">

**PP V2 Before**
<img width="1382" alt="PP - Before" src="https://github.com/user-attachments/assets/0a3b1cba-0d78-406d-876b-4c208aaec4ff">

**PP V2 After**
<img width="1382" alt="PP - After" src="https://github.com/user-attachments/assets/9434282b-93f7-4d76-8987-c997d502616b">

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2024-10-01 09:02 UTC, mahamakifdar19 commented on src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
> +  const markerSizes = calculateMarkerSizes();
@muhammad-ammar I think keeping the marker size calculation outside of the `ScatterChart` makes the chart more flexible and reusable. By passing the marker sizes as props, we can easily adjust the calculation logic for different use cases. If we embed the logic in the chart, maintaining and extending it for other components that might need different attributes for bubble size could become more complex in the future.

2024-10-02 09:54 UTC, saleem-latif requested changes

2024-10-02 09:54 UTC, saleem-latif commented on src/components/AdvanceAnalyticsV2/charts/ScatterChart.jsx
> +        size: filteredData.map(item => {
map already passes index to the function. Here is an example
```
const numbers = [1, 2, 3, 4];
const filteredNumbers = numbers.map((num, index) => {
  if (index < 3) {
    return num;
  }
});
```
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#mapped_array_contains_undefined

2024-10-02 10:28 UTC, saleem-latif approved these changes

2024-10-02 12:22 UTC, muhammad-ammar approved these changes

2024-10-02 13:05 UTC, jajjibhai008 approved these changes

2024-10-03 07:15 UTC, merged