feat: creates a modal to add members
openedx/frontend-app-admin-portal pull request #1363
Opened 2024-12-04 16:22 UTC by katrinan029

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2024-12-12 20:58 UTC, kiram15 approved these changes

2024-12-12 21:52 UTC, kiram15 requested changes

2024-12-12 21:52 UTC, kiram15 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +          defaultMessage="Create a custom group of members"
This title isn't needed for the Add members modal

2024-12-12 21:52 UTC, kiram15 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +          <h4 className="mt-4">Group Name</h4>
"Group name" should be all caps, should add className="text-uppercase"

2024-12-12 21:52 UTC, kiram15 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +          <p>Only members registered with your organization can be added to your group. Learn more</p>
Even though we might not have the help center doc yet, I think we could make this a hyperlink that just points to edx.org or something

2024-12-12 21:52 UTC, kiram15 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +              id="people.management.page.create.group.csv.upload"
When I upload a large CSV, I'm getting two error states. I don't see any examples of this in Figma, and I think we might need to talk to Sophia about which one should be present 
<img width="645" alt="Screenshot 2024-12-12 at 2 48 32 PM" src="https://github.com/user-attachments/assets/8423ce30-f68c-47bf-b75d-04cddbd908bb" />

2024-12-12 21:52 UTC, kiram15 commented on src/components/PeopleManagement/AddMemberTableAction.jsx
> +  <Button iconBefore={Add} onClick={openModal} variant="outline-primary">Add members</Button>
I'm not actually seeing this button as a table action? The only way I'm able to open up the add members modal is a weird stray edit icon on the Group Detail card after the "View group progress" button 
<img width="1354" alt="Screenshot 2024-12-12 at 2 51 56 PM" src="https://github.com/user-attachments/assets/6bcce786-1db3-4e86-93b5-b2eb79bad4c6" />

2025-01-02 19:00 UTC, katrinan029 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +              id="people.management.page.create.group.csv.upload"
thanks for this catch! we should only be showing "Members can't be invited as entered" for large csv uploads.

2025-01-02 21:12 UTC, katrinan029 commented on src/components/PeopleManagement/AddMemberTableAction.jsx
> +  <Button iconBefore={Add} onClick={openModal} variant="outline-primary">Add members</Button>
I think the pr wasn't updated at that time, please try again!

2025-01-06 18:53 UTC, katrinan029 commented on src/components/PeopleManagement/AddMembersModalContent.jsx
> +              id="people.management.page.create.group.csv.upload"
we're going to keep both error messages!

2025-01-06 23:25 UTC, kiram15 approved these changes
Everything looks good! There one little problem with data table selected numbers that we might want to look into though (says zero selected after I've selected 3 new members) 
<img width="335" alt="Screenshot 2025-01-06 at 4 22 37 PM" src="https://github.com/user-attachments/assets/e6eeee34-1ec9-4d44-bd35-6812ecb18714" />

2025-01-06 23:25 UTC, kiram15 commented on src/components/PeopleManagement/tests/AddMembersModal.test.jsx
> +  it('renders as expected', async () => {
Great test coverage!

2025-01-07 21:54 UTC, merged