feat!: adding in the full stepper
openedx/frontend-app-admin-portal pull request #985
Opened 2023-04-28 04:46 UTC by kiram15

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2023-04-28 04:47 UTC, kiram15 commented on src/components/forms/data/reducer.ts
> +  if (typeof state.currentStep?.validations == "boolean") {
TODO: fix this validation because its still allowing us to progress if we haven't selected one

2023-05-01 00:47 UTC, kiram15 commented on src/components/settings/SettingsLMSTab/LMSSelectorPage.tsx
> +    const handleChange = e => setLms(e.target.value);
The only reason I didn't implement it this way is to use the updateFormFieldsAction, we have to have access to the dispatch in the component hierarchy, which we don't at this stage. I can wrap it in later by populating it, but I don't see how I could do it in this file.

2023-05-01 16:48 UTC, marlonkeating commented on src/components/settings/SettingsLMSTab/LMSFormWorkflowConfig.tsx
> +import SAPFormConfig, { SAPConfigCamelCase, SAPConfigSnakeCase } from "./LMSConfigs/SAP/SAPConfig";
Need .ts(x) file extensions on these imports.

2023-05-02 23:34 UTC, marlonkeating requested changes

2023-05-03 14:17 UTC, kiram15 commented on src/components/settings/SettingsLMSTab/LMSFormWorkflowConfig.tsx
> +    (lms && lms !== '') &&
https://stackoverflow.com/questions/8970008/can-we-rely-on-string-isempty-for-checking-null-condition-on-a-string-in-java
Lodash will throw a null pointer if its undefined though, I still need the lms check

2023-05-03 15:33 UTC, marlonkeating approved these changes

2023-05-03 16:41 UTC, merged